import type { Translation } from './types'

export const en: Translation = {
  meta: {
    title: 'Inspechron — AI Technical Inspection App for Home Inspectors',
    description:
      'Inspect faster with AI: detect cracks, moisture, and defects in the field. Generate professional PDF reports in seconds. Free trial on Google Play.',
    ogTitle: 'Inspechron — AI Technical Inspection for Home Inspectors',
    ogDescription:
      'Detect field defects and deliver professional reports in seconds. Free app trial on Google Play.',
    keywords:
      'technical inspection, AI inspection app, PDF reports, home inspectors, inspection software, construction, Inspechron, property inspection, inspection report PDF',
  },
  nav: {
    features: 'Features',
    pricing: 'Pricing',
    faq: 'FAQ',
    investors: 'Investors',
    contact: 'Contact',
    download: 'Download',
  },
  a11y: {
    skipToContent: 'Skip to content',
    mainNav: 'Main navigation',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    languageSelector: 'Select language',
    footerNav: 'Footer',
  },
  hero: {
    badge: 'Available on Google Play · Active pilot',
    headline: 'AI-powered technical inspection in real time',
    slogan: 'From hours of manual documentation to professional reports in seconds.',
    subtitle:
      'Capture field evidence, automatically detect defects, and generate professional reports ready for clients, contractors, builders, and insurers.',
    ctaPrimary: 'Try for free',
    ctaSecondary: 'Request B2B demo',
    mockupAlt: 'Inspechron app: AI-powered technical inspection and defect detection',
    mockupPlaceholder: 'Add your screenshot at /public/screenshots/hero-mockup.png',
  },
  problemSolution: {
    title: 'From hours of manual work to professional reports in seconds',
    subtitle:
      'Reduce documentation, evidence organization, and report generation time by up to 80%.',
    problemTitle: 'The problem today',
    problems: [
      'Evidence scattered across WhatsApp, email, and photo galleries',
      'Hours lost documenting findings after every inspection',
      'Risk of human error and undetected defects',
      'Fragmented information between inspectors, contractors, and office',
    ],
    solutionTitle: 'The Inspechron solution',
    solutions: [
      'Automatically detect damage while you inspect',
      'Centralize all evidence in one place',
      'Generate professional reports in seconds',
      'Scale operations without increasing administrative workload',
    ],
  },
  walkthrough: {
    title: 'Less documentation. More inspections.',
    subtitle:
      'Capture evidence, detect damage, and generate professional reports with AI.',
    steps: [
      {
        title: 'Welcome to Inspechron',
        tagline: 'Start a professional inspection in seconds',
        description:
          'Set up your project and start documenting findings from the first second.',
        imageAlt: 'Inspechron home screen — AI technical inspection app for home inspectors',
      },
      {
        title: 'Dashboard',
        tagline: 'Your entire operation in one place',
        description:
          'Projects, inspections, and reports organized — no spreadsheets or WhatsApp.',
        imageAlt: 'Inspechron dashboard with organized technical inspection projects',
      },
      {
        title: 'Create project',
        tagline: 'Never lose control of a property',
        description:
          'Every property stays organized with its history, evidence, and reports.',
        imageAlt: 'Create a property inspection project in the Inspechron app',
      },
      {
        title: 'Create sections',
        tagline: 'Structured and consistent inspections',
        description:
          'Divide each property by area to document everything without omissions.',
        imageAlt: 'Inspection sections by area for structured property walkthroughs',
      },
      {
        title: 'AI detection',
        tagline: 'Detect problems before they cost money',
        description:
          'AI identifies cracks, moisture, mold, and defects while you inspect.',
        imageAlt: 'AI crack and moisture detection during a field technical inspection',
      },
      {
        title: 'PDF report',
        tagline: 'Deliver professional reports in seconds',
        description:
          'Generate reports ready for clients, contractors, or insurers with one click.',
        imageAlt: 'Professional PDF technical inspection report generated by Inspechron',
      },
    ],
  },
  promoBanner: {
    alt: 'Inspechron — AI-powered inspection platform',
  },
  seoContent: {
    title: 'AI technical inspection software for professional home inspectors',
    paragraphs: [
      'Property and building inspections require accuracy, documented evidence, and clear reports for clients, builders, and insurers. Yet many independent inspectors still lose hours organizing photos, writing findings, and assembling reports manually.',
      'Inspechron is an AI-assisted technical inspection app built for professionals who need to inspect faster, reduce errors, and deliver quality PDF reports in minutes — not hours.',
    ],
    subsections: [
      {
        title: 'Who is Inspechron for?',
        text: 'Independent home inspectors, property managers, quality control firms, builders, and insurance adjusters performing move-in, move-out, pre-purchase, or damage assessments. If you document properties in the field and deliver technical reports to third parties, Inspechron centralizes the entire workflow in one app.',
      },
      {
        title: 'Real-time AI inspection',
        text: 'During the visit, you capture photo evidence and AI automatically detects defects such as cracks, moisture, paint deterioration, and other visible issues. Every image is linked to the project, property, and inspected area — no more evidence scattered across WhatsApp or phone galleries.',
      },
      {
        title: 'Professional PDF reports in seconds',
        text: 'When the inspection is complete, generate a PDF technical report ready to deliver. It includes organized evidence, AI-assisted analysis, and a professional format that strengthens the inspector’s credibility with clients and insurers.',
      },
      {
        title: 'Start free on Google Play',
        text: 'Try Inspechron with no mandatory subscription. Download the app, get welcome credits, and run your first AI-assisted technical inspection. Pay only when you generate a complete professional report.',
      },
    ],
  },
  features: {
    title: 'Key Features',
    subtitle:
      'Inspect faster, document better, and generate professional reports with AI.',
    items: [
      {
        title: 'Inspect faster',
        description:
          'Get real-time assistance while inspecting and reduce time in the field.',
      },
      {
        title: 'Detect damage with AI',
        description:
          'Identify cracks, moisture, and paint deterioration with intelligent analysis.',
      },
      {
        title: 'Generate reports in seconds',
        description:
          'Create professional reports ready to deliver with evidence and technical analysis.',
      },
      {
        title: 'Organize properties and projects',
        description:
          'Manage inspections, properties, and findings from a single platform.',
      },
      {
        title: 'Never lose evidence',
        description:
          'Every photo is automatically linked to the property, area, and corresponding finding.',
      },
      {
        title: 'Your information always protected',
        description:
          'Never lose a report. Your inspections are backed up and organized automatically.',
      },
    ],
  },
  audience: {
    title: 'Who uses Inspechron?',
    subtitle:
      'Built for professionals who need to inspect faster, document better, and reduce operational costs.',
    segments: [
      {
        title: 'Independent Inspectors',
        description:
          'Generate more reports in less time with AI-powered professional documentation.',
      },
      {
        title: 'Property Managers',
        description:
          'Centralize inspections, photo evidence, and reports on a single platform.',
      },
      {
        title: 'Builders and Inspection Companies',
        description:
          'Detect damage, document findings, and deliver professional reports to clients and contractors.',
      },
      {
        title: 'Insurance Adjusters and Appraisers',
        description:
          'Document technical evidence and generate consistent reports for assessments and claims.',
      },
    ],
  },
  pricing: {
    title: 'Simple, transparent pricing',
    subtitle: 'Start free. Pay only when you generate a professional report.',
    free: {
      title: 'Free Trial',
      price: '$0',
      description:
        'Get welcome credits to try Inspechron with no commitment.',
      features: [
        'Real-time AI damage detection',
        'Project and property organization',
        'Welcome credits included',
        'No credit card required',
      ],
    },
    payPerReport: {
      title: 'Professional AI Report',
      badge: 'Most Popular',
      price: '$11.99',
      priceSuffix: '/ report',
      description: '1 credit = 1 complete technical report',
      features: [
        'Professional PDF report ready to deliver',
        'Documented photo evidence',
        'AI-generated technical analysis',
        'Automatic risk classification',
      ],
    },
    comingSoon: {
      title: 'Team Plans (Coming Soon)',
      description:
        'Advanced roles, multi-user collaboration, inspector management, and enterprise billing.',
    },
    cta: 'Start free on Google Play',
  },
  socialProof: {
    title: 'Early traction',
    badges: [
      'Available on Google Play',
      'Active pilot with inspectors',
      'Production platform',
      'Advanced AI + automated reports',
    ],
    testimonialPlaceholder:
      'Reserved space for pilot inspector testimonials. Add real quotes when available.',
  },
  faq: {
    title: 'Frequently asked questions',
    items: [
      {
        question: 'Can I really generate professional reports in seconds?',
        answer:
          'Yes. Inspechron automates damage detection, organizes photo evidence, and generates technical reports ready to deliver, significantly reducing manual documentation time.',
      },
      {
        question: 'What types of damage can the AI detect?',
        answer:
          'The AI is currently trained to identify cracks, moisture, mold, paint deterioration, and other common visible defects during a technical inspection.',
      },
      {
        question: 'How does the credit system work?',
        answer:
          'You receive welcome credits to try the platform. Each credit allows you to generate one complete professional technical report. You only pay when you need to generate new reports.',
      },
      {
        question: 'Do I need internet to use the application?',
        answer:
          'Photos can be captured in the field. AI detection and report generation require a connection to process information securely in the cloud.',
      },
      {
        question: 'Who uses Inspechron?',
        answer:
          'Independent inspectors, inspection companies, builders, property managers, adjusters, and professionals who need to document findings quickly and accurately.',
      },
      {
        question: 'Are my data and reports secure?',
        answer:
          'Yes. All photos, projects, and reports are stored securely and remain organized and available whenever you need them.',
      },
      {
        question: 'Is it available for companies and teams?',
        answer:
          'Yes. Inspechron is designed for both independent professionals and organizations managing multiple inspections, properties, or projects.',
      },
      {
        question: 'What platforms is it available on?',
        answer:
          'Inspechron is currently available for Android via Google Play. New platforms and enterprise features will be added soon.',
      },
      {
        question: 'How much time can I save with Inspechron?',
        answer:
          'Many professionals significantly reduce the time spent documenting findings, organizing photos, and writing reports, allowing them to complete more inspections in less time.',
      },
    ],
  },
  investors: {
    title: 'Opportunity for investors and strategic partners',
    subtitle:
      'Inspechron is transforming technical documentation through artificial intelligence, automating processes that still consume hours of manual work.',
    badge: 'Investment opportunity',
    whyNowTitle: 'Why now?',
    whyNowText:
      'Thousands of inspections are still documented manually with scattered photos, spreadsheets, and hours spent writing reports. Inspechron reduces that process to seconds through artificial intelligence.',
    bullets: [
      {
        title: 'Growing market',
        description:
          'Inspectors, builders, insurers, property managers, and quality control companies.',
      },
      {
        title: 'Operational product',
        description:
          'Available on Google Play with pilot users and report generation in production.',
      },
      {
        title: 'Proprietary technology',
        description:
          'AI-assisted visual detection and automated generation of technical reports.',
      },
      {
        title: 'Scalable model',
        description:
          'Pay-per-report with a credit system and expansion toward enterprise licenses.',
      },
      {
        title: 'Competitive advantage',
        description:
          'Real-time detection during inspection and professional report delivery in seconds.',
      },
    ],
    contact: 'Contact for investment or partnership:',
    cta: 'Talk to the founding team',
  },
  finalCta: {
    title: 'Start generating professional reports in seconds',
    subtitle:
      'Download Inspechron for free and turn hours of manual documentation into technical reports ready to deliver.',
    supportText:
      'Detect damage, organize evidence, and generate professional reports from a single application.',
    ctaPrimary: 'Try Free on Google Play',
    ctaSecondary: 'Request B2B Demo',
    trustCopy:
      'No mandatory subscription. Welcome credits included so you can try your first inspection.',
  },
  floatingCta: {
    label: '🚀 Try Free',
    ariaLabel: 'Try Inspechron for free on Google Play',
  },
  footer: {
    tagline: 'Intelligent real-time inspection',
    product: 'Product',
    resources: 'Resources',
    legal: 'Legal',
    contact: 'Contact',
    privacy: 'Privacy policy',
    playStore: 'Google Play',
    followUs: 'Follow us',
    copyright: '© 2026 Inspechron. All rights reserved.',
    inspectionPage: 'Home inspection',
    inspectorsPage: 'For inspectors',
    reportPage: 'PDF reports',
  },
}
